from .client_service import ClienteService
from .recolecc_service import RecoleccService
from .city_service import CiudadService
from .residuos_service import ResiduosCliService
from .auth_service import AuthService
from .clienpot import ClipotService
from .resclipot import ResCliPotService
from .tiposresid import TipoResidService
from .logistica_service import LogisticaService
from .frecuencia_service import FrecuenciaService