services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.project1-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.project1-https.tls=true
      - traefik.http.routers.project1-https.tls.certresolver=le
      - traefik.http.services.project1-service.loadbalancer.server.port=8000
    networks:
      - traefik-public
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  traefik-public:
    external: true  