services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
    - DB_URL=${DB_URL}
    - DOMAIN=${DOMAIN}
    - SECRET_KEY=${SECRET_KEY}
    - ALGORITHM=${ALGORITHM}
    - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    - MAIL_USERNAME=${MAIL_USERNAME}
    - MAIL_PASSWORD=${MAIL_PASSWORD}
    - MAIL_FROM=${MAIL_FROM}
    - MAIL_PORT=${MAIL_PORT}
    - MAIL_SERVER=${MAIL_SERVER}
    - MAIL_TLS=${MAIL_TLS}
    - MAIL_SSL=${MAIL_SSL}
    restart: always
    ports:
      - "8000:8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.project1-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.project1-https.tls=true
      - traefik.http.routers.project1-https.tls.certresolver=le
      - traefik.http.services.project1-service.loadbalancer.server.port=8000
    networks:
      - traefik-public
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  traefik-public:
    external: true  
