services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
    - DB_URL=${DB_URL}
    - DOMAIN=${DOMAIN}
    restart: always
    ports:
      - "8000:8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.project1-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.project1-https.tls=true
      - traefik.http.routers.project1-https.tls.certresolver=le
      - traefik.http.services.project1-service.loadbalancer.server.port=8000
    networks:
      - traefik-public
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  traefik-public:
    external: true  
